// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "URL Shortener",
    "title": "URL Shortener",
    "version": "2.0.0"
  },
  "paths": {
    "/url/getShortUrl/{URL}": {
      "get": {
        "tags": [
          "URL Shortened API"
        ],
        "summary": "Get Shortened URL",
        "operationId": "getShortenerUrl",
        "parameters": [
          {
            "type": "string",
            "description": "Long URL that need to be shortened",
            "name": "URL",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "getShortenerUrl API \"Successful\"",
            "schema": {
              "$ref": "#/definitions/getShortenedUrlResp"
            }
          },
          "401": {
            "description": "Unauthorised",
            "schema": {
              "$ref": "#/definitions/errorInformation"
            }
          },
          "500": {
            "description": "getAimlConfigInfo API Failed \"Internal Server Error\"",
            "schema": {
              "$ref": "#/definitions/errorInformation"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "errorInformation": {
      "description": "Problem as defined in https://tools.ietf.org/html/rfc7807",
      "type": "object",
      "title": "errorInformation",
      "required": [
        "detail",
        "status"
      ],
      "properties": {
        "detail": {
          "description": "A human-readable explanation specific to this occurrence of the problem.",
          "type": "string",
          "example": "Info not found"
        },
        "status": {
          "description": "The HTTP status code for this occurrence of the problem.",
          "type": "integer",
          "format": "int32",
          "example": 404
        }
      }
    },
    "getShortenedUrlResp": {
      "type": "object",
      "title": "getShortenedUrlResp",
      "properties": {
        "ShortURL": {
          "description": "Shortened URL",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "URL Shortener",
    "title": "URL Shortener",
    "version": "2.0.0"
  },
  "paths": {
    "/url/getShortUrl/{URL}": {
      "get": {
        "tags": [
          "URL Shortened API"
        ],
        "summary": "Get Shortened URL",
        "operationId": "getShortenerUrl",
        "parameters": [
          {
            "type": "string",
            "description": "Long URL that need to be shortened",
            "name": "URL",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "getShortenerUrl API \"Successful\"",
            "schema": {
              "$ref": "#/definitions/getShortenedUrlResp"
            }
          },
          "401": {
            "description": "Unauthorised",
            "schema": {
              "$ref": "#/definitions/errorInformation"
            }
          },
          "500": {
            "description": "getAimlConfigInfo API Failed \"Internal Server Error\"",
            "schema": {
              "$ref": "#/definitions/errorInformation"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "errorInformation": {
      "description": "Problem as defined in https://tools.ietf.org/html/rfc7807",
      "type": "object",
      "title": "errorInformation",
      "required": [
        "detail",
        "status"
      ],
      "properties": {
        "detail": {
          "description": "A human-readable explanation specific to this occurrence of the problem.",
          "type": "string",
          "example": "Info not found"
        },
        "status": {
          "description": "The HTTP status code for this occurrence of the problem.",
          "type": "integer",
          "format": "int32",
          "example": 404
        }
      }
    },
    "getShortenedUrlResp": {
      "type": "object",
      "title": "getShortenedUrlResp",
      "properties": {
        "ShortURL": {
          "description": "Shortened URL",
          "type": "string"
        }
      }
    }
  }
}`))
}
