// Code generated by go-swagger; DO NOT EDIT.

package url_shortened_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetShortenerURLParams creates a new GetShortenerURLParams object
// no default values defined in spec.
func NewGetShortenerURLParams() GetShortenerURLParams {

	return GetShortenerURLParams{}
}

// GetShortenerURLParams contains all the bound params for the get shortener Url operation
// typically these are obtained from a http.Request
//
// swagger:parameters getShortenerUrl
type GetShortenerURLParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Long URL that need to be shortened
	  Required: true
	  In: path
	*/
	URL string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetShortenerURLParams() beforehand.
func (o *GetShortenerURLParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rURL, rhkURL, _ := route.Params.GetOK("URL")
	if err := o.bindURL(rURL, rhkURL, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetShortenerURLParams) bindURL(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.URL = raw

	return nil
}
